---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: route-patch-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: route-patch-controller
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["route.openshift.io"] # "" indicates the core API group
    resources: ["routes"]
    verbs: ["get", "watch", "list", "patch"]
---
apiVersion: ""
kind: ClusterRoleBinding
metadata:
  name: route-patch-controller
subjects:
  - kind: ServiceAccount
    name: route-patch-controller
roleRef:
  kind: ClusterRole
  name: route-patch-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-patch-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: route-patch-controller
  template:
    metadata:
      labels:
        app: route-patch-controller
    spec:
      containers:
        - name: controller
          image: ghcr.io/sorend/route-patch-controller:latest
          env:
            - name: SERVICE_INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          resource:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 300m
              memory: 500Mi
      volumes:
        - name: config
          configMap:
            name: route-patch-controller
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: route-patch-controller
data:
  application.properties: |
    service.namespace-router-label = router
    service.default-router = apps
    service.router-domains."apps" = apps.mycluster.com
    service.router.domains."prod" = prod.mycluster.com
    service.router.domains."dev" = dev.mycluster.com
