
name: Build

on: [push, pull_request]

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Install docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
      - name: Run tests
        run: |
          ./gradlew quarkusBuild
          ./gradlew check

  pack-and-publish:
    name: Pack and publish
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Publish
        run: |
          echo "TODO"
