
name: Build

on: [push, pull_request]

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '17'
      - name: Install quarkus cli
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
      - name: Install podman
        run: |
          sudo apt-get -y update
          sudo apt-get -y install podman
          # curl -fsSL https://get.docker.com -o get-docker.sh
          # sh get-docker.sh
      - name: Run tests
        run: |
          quarkus build --native

  pack-and-publish:
    name: Pack and publish
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Publish
        run: |
          echo "TODO"
