
name: Build

on: [push, pull_request]

jobs:
  run-tests:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_target: [ 'linux/amd64', 'linux/arm64']
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '17'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.docker_target }}
      - name: Install quarkus cli
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
      - id: get_version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - run: echo ${{ steps.get_version.outputs.version-without-v }}
      - name: Quarkus Build ${{ matrix.docker_target }}
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          PATH=$PATH:~/.jbang/bin quarkus build \
            --native \
            -Dquarkus.devservices.enabled=false \
            -Dquarkus.docker.buildx.platform=${{ matrix.docker_target }} \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.registry=ghcr.io \
            -Dquarkus.container-image.group=sorend \
            -Dquarkus.container-image.name=route-patch-controller \
            -Dquarkus.container-image.tag=${{ steps.get_version.outputs.version }} \
            -Dquarkus.container-image.additional-tags=latest \
            -Dquarkus.container-image.username=$GHCR_USERNAME \
            -Dquarkus.container-image.password=$GHCR_TOKEN
