
name: Build

on: [push, pull_request]

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '17'
      - name: Install quarkus cli
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
      - id: get_version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - run: echo ${{ steps.get_version.outputs.version-without-v }}
      - name: Run tests
        run: |
          PATH=$PATH:~/.jbang/bin quarkus build -Dquarkus.container-image.build=true

  pack-and-publish:
    name: Pack and publish
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '17'
      - name: Publish
        run: |
          docker image ls
          echo "TODO"
